[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]

solc = "0.8.20"
optimizer = true
optimizer_runs = 100
sizes = true


[rpc_endpoints]
mainnet = "https://mainnet.infura.io/v3/${INFURA_KEY}"
sepolia = "https://sepolia.infura.io/v3/${INFURA_KEY}"
polygon = "https://polygon.infura.io/v3/${INFURA_KEY}"



[etherscan]
mainnet = {key = "${ETHERSCAN_API_KEY}" }
sepolia = {key = "${ETHERSCAN_API_KEY}" }
polygon = {key = "${POLYGONSCAN_API_KEY}", chain = 137, url = "https://api.polygonscan.com/api/" }


# See more config options https://github.com/foundry-rs/foundry/tree/master/config